// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using Hashtable = ExitGames.Client.Photon.Hashtable;

static class PhotonViewExtensions
{
	public static bool attachedToPlayer(this PhotonView photonView, PhotonPlayer player)
	{
		return photonView.owner == player;
	}

	public static bool isLocal(this PhotonView photonView)
	{
		return photonView.owner.isLocal;
	}

	public static T GetComponent<T>(this PhotonView photonView) where T: Component
	{
		return photonView.transform.root.GetComponent<T>();
	}

	public static void setCrossedFinishLine(this PhotonView photonView, bool crossed)
	{
		photonView.owner.setCrossedFinishLine(crossed);
	}

	public static int playerNumber(this PhotonView photonView)
	{
		return photonView.owner.playerNumber();
	}

	public static void incrementTotalPoints(this PhotonView photonView, int points)
	{
		photonView.owner.incrementTotalPoints(points);
	}
}
