// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

namespace AssemblyCSharp
{

	/*				*
	-1 				+1
	 * 				*
	 *	1  2  3	 4  */

	public class PlayerStartPositionProvider
	{
		public static List<Vector3> startPositionsForMaxPlayers(int maxPlayers)
		{
			List<Vector3> positions = new List<Vector3>();

			float levelWidth = 2;
			float spacing = levelWidth / (maxPlayers + 1);
			int leftXEdge = -1;

			for (int i = 1; i <= maxPlayers; ++i)
			{
				float xPostiion = leftXEdge + spacing * i;
				Vector3 position = new Vector3(xPostiion, 1);
				positions.Add(position);
			}

			return positions;
		}
	}
}

